### ISSUE TITLE
Where?

### ISSUE THREAD

**Issue by remotevase** [mariobrostech/mariobrostech.github.io#1]
@mariobrostech where do you get your swf files from?

**Comment by mariobrostech** [comment]
Absolutely everywhere. You just have to hunt around on Google for a good
one. Just Google something like Boomboot 2 HTML codes, inspect the frame
with the game, and copy the SWF. Then, download it and load it into your
website!

**Comment by remotevase** [comment]
The problem is that chrome now has a built in SWF loader so it does not download

**Comment by mariobrostech** [comment]
Yeah, right-click and save as. If that doesn't work, get another browser
(or use Edge/IE) to download them.
