### ISSUE TITLE
#REMIX!

### ISSUE THREAD

**Issue by TheRoyalBlock** [mariobrostech/mariobrostech.github.io#2]
I am working on a remix of this for my own site. It will hopefully look pretty different lol

**Comment by TheRoyalBlock** [comment]
Never mind, I changed my mind.

**Comment by mariobrostech** [comment]
What?! XD

**Comment by TheRoyalBlock** [comment]
maybe I will remix it. IDK

**Comment by mariobrostech** [comment]
Please don't remix this, make it yourself. Just lookup basic bootstrap skills!
